stages:        
  - build
#   - test
#   - deploy

build-job:      
  stage: build
  script:
      # Check if a code is correctly compiled.
      - (cd neural_network_one_dim_SGD && ./compile_run.sh)
# unit-test-job:  
#   stage: test    
#   script:

# lint-test-job:   
#   stage: test   
#   script:

# deploy-job:      
#   stage: deploy  
#   script: