image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:        
  - build

build-job:
  stage: build
  image: gcc:latest
  script:
    # Check the basic function first.
    - (cd test && ./compile_run.sh)
    
    # Then, check a neural network itself.
    - (cd neural_network_one_dim_SGD && ./compile_run.sh)
