image: docker:latest
# services:
#   - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - before_build
  - omit_error
  - build

before-build:
  stage: before_build
  image: docker:latest
  script:
    # Send OK to the client
    - echo "build OK.";

# Check if the error is produced properly
# This is for the test if an error is produced.
before-build-error:
  stage: omit_error
  image: docker:latest
  script:
    # Send Error to the client as a test
    - echo "error" 1>&2;
    - exit 125;
  only: 
    - /^error\/\d{4}_\d{2}_\d{2}$/

build-job:
  stage: build
  image: gcc:latest
  script:
    # Check the basic function first.
    - (cd test && ./compile_run.sh)
    
    # Then, check a neural network itself.
    # TODO: Just allow a user to make a small test sample for linear_regression.
    # - (cd neural_network_one_dim_SGD && ./compile_run.sh)
