image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:        
  - build

before_script:
  - docker info

build-job:
  stage: build
  script:
    - echo 'build success.'
    # - (cd neural_network_one_dim_SGD && ./compile_run.sh)